import crypto from 'node:crypto';

export const fallbackCareers = [
  {
    id: 1,
    career_name_th: 'นักวิเคราะห์ข้อมูล',
    career_name_en: 'Data Analyst',
    category: 'สายเทคโนโลยีและดิจิทัล',
    description: 'แปลงข้อมูลให้เป็น insight เพื่อช่วยตัดสินใจในธุรกิจ นโยบาย หรือบริการสาธารณะ',
    required_skills_json: '["analytical","technology","communication"]',
    interest_tags_json: '["data","technology","business"]',
    personality_tags_json: '["analytical","communication"]',
    education_hint: 'เหมาะกับผู้สนใจสถิติ spreadsheet, SQL, dashboard หรือ data storytelling',
    roadmap: 'เริ่มจาก Spreadsheet -> SQL เบื้องต้น -> ทำ dashboard -> วิเคราะห์ dataset จริง -> ทำ portfolio 2-3 ชิ้น',
    trend_score: 88,
    popularity_score: 86,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
  {
    id: 2,
    career_name_th: 'นักพัฒนาซอฟต์แวร์',
    career_name_en: 'Software Developer',
    category: 'สายเทคโนโลยีและดิจิทัล',
    description: 'สร้างเว็บ แอป และระบบดิจิทัลที่แก้ปัญหาให้ผู้ใช้หรือองค์กร',
    required_skills_json: '["technology","analytical","independence"]',
    interest_tags_json: '["technology","business"]',
    personality_tags_json: '["technology","independence"]',
    education_hint: 'เริ่มได้จาก HTML/CSS/JavaScript แล้วต่อยอด React, API และฐานข้อมูล',
    roadmap: 'ฝึกเขียนเว็บเล็ก ๆ -> เชื่อม API -> ทำระบบ login mock -> deploy portfolio -> อ่าน code review',
    trend_score: 90,
    popularity_score: 88,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
  {
    id: 3,
    career_name_th: 'วิศวกรปัญญาประดิษฐ์',
    career_name_en: 'AI Engineer',
    category: 'สายเทคโนโลยีและดิจิทัล',
    description: 'ออกแบบระบบ AI ที่ช่วยวิเคราะห์ สร้างคำตอบ หรืออัตโนมัติงานบางส่วนอย่างรับผิดชอบ',
    required_skills_json: '["technology","analytical","creativity"]',
    interest_tags_json: '["technology","data"]',
    personality_tags_json: '["technology","analytical"]',
    education_hint: 'ต้องมีพื้นฐาน programming, data, model evaluation และจริยธรรม AI',
    roadmap: 'เรียน Python -> data preprocessing -> ใช้ API/LLM -> ทดลอง model evaluation -> ทำ AI assistant prototype',
    trend_score: 94,
    popularity_score: 84,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
  {
    id: 4,
    career_name_th: 'ผู้เชี่ยวชาญ SEO',
    career_name_en: 'SEO Specialist',
    category: 'สายการตลาดออนไลน์',
    description: 'วิเคราะห์คำค้นหาและปรับเนื้อหาให้คนเจอเว็บไซต์ผ่าน search engine มากขึ้น',
    required_skills_json: '["analytical","content","business"]',
    interest_tags_json: '["marketing","data","content"]',
    personality_tags_json: '["analytical","business"]',
    education_hint: 'เหมาะกับคนที่ชอบภาษา ข้อมูล และพฤติกรรมผู้ใช้',
    roadmap: 'เรียน keyword research -> ปรับบทความ -> วัดผล analytics -> ทำ content plan -> ทดลอง A/B headline',
    trend_score: 82,
    popularity_score: 80,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
  {
    id: 5,
    career_name_th: 'คอนเทนต์ครีเอเตอร์',
    career_name_en: 'Content Creator',
    category: 'สายการตลาดออนไลน์',
    description: 'เล่าเรื่อง สร้างสื่อ และออกแบบเนื้อหาให้แบรนด์หรือสังคมเข้าใจง่ายและน่าติดตาม',
    required_skills_json: '["creativity","content","communication"]',
    interest_tags_json: '["art","marketing","content"]',
    personality_tags_json: '["creativity","communication"]',
    education_hint: 'เหมาะกับคนที่ชอบเล่าเรื่อง ภาพ เสียง วิดีโอ หรือคอนเทนต์สั้น',
    roadmap: 'เลือก niche -> ทำ content calendar -> ผลิตคลิป/โพสต์ -> อ่าน analytics -> ปรับ format ให้ดีขึ้น',
    trend_score: 86,
    popularity_score: 90,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
  {
    id: 6,
    career_name_th: 'นักการตลาด Performance',
    career_name_en: 'Performance Marketer',
    category: 'สายการตลาดออนไลน์',
    description: 'วางแผน ยิงแคมเปญ และวิเคราะห์ผลโฆษณาออนไลน์ด้วยตัวเลข',
    required_skills_json: '["business","analytical","communication"]',
    interest_tags_json: '["marketing","data","business"]',
    personality_tags_json: '["business","analytical"]',
    education_hint: 'ควรเข้าใจ funnel, ads platform, analytics และการทดลองแบบวัดผลได้',
    roadmap: 'เรียน marketing funnel -> ตั้ง campaign mock -> อ่าน metric -> ทำรายงาน insight -> optimize budget',
    trend_score: 87,
    popularity_score: 82,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
  {
    id: 7,
    career_name_th: 'นักเขียนบทความ',
    career_name_en: 'Article Writer',
    category: 'อาชีพอิสระ / Freelance',
    description: 'เขียนบทความให้ความรู้ รีวิว หรือสื่อสารเรื่องยากให้เข้าใจง่าย',
    required_skills_json: '["content","creativity","communication"]',
    interest_tags_json: '["art","content","freelance"]',
    personality_tags_json: '["creativity","independence"]',
    education_hint: 'เหมาะกับผู้ชอบค้นคว้า เขียน และจัดโครงเรื่อง',
    roadmap: 'ฝึกเขียนบทความ 800 คำ -> ทำ portfolio -> เรียน SEO พื้นฐาน -> รับ brief -> ปรับงานจาก feedback',
    trend_score: 76,
    popularity_score: 78,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
  {
    id: 8,
    career_name_th: 'นักออกแบบกราฟิก',
    career_name_en: 'Graphic Designer',
    category: 'อาชีพอิสระ / Freelance',
    description: 'ออกแบบภาพ สื่อ และ visual identity ให้สื่อสารชัดและน่าจดจำ',
    required_skills_json: '["creativity","communication","business"]',
    interest_tags_json: '["art","marketing","freelance"]',
    personality_tags_json: '["creativity","independence"]',
    education_hint: 'เหมาะกับผู้สนใจภาพ สี typography และ brand communication',
    roadmap: 'เรียน design principles -> ทำ poster/social set -> ฝึก brief จริง -> ทำ portfolio -> รับ feedback',
    trend_score: 78,
    popularity_score: 82,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
  {
    id: 9,
    career_name_th: 'นักตัดต่อวิดีโอ',
    career_name_en: 'Video Editor',
    category: 'อาชีพอิสระ / Freelance',
    description: 'เรียบเรียงภาพ เสียง และจังหวะให้คอนเทนต์น่าสนใจและเล่าเรื่องได้ดี',
    required_skills_json: '["content","creativity","technology"]',
    interest_tags_json: '["art","content","freelance"]',
    personality_tags_json: '["creativity","independence"]',
    education_hint: 'เหมาะกับผู้ชอบ storytelling, rhythm และเครื่องมือสร้างสื่อ',
    roadmap: 'ฝึกตัดคลิปสั้น -> เรียน sound/title -> ทำ before-after reel -> ทดลอง format หลายแบบ -> ทำ showreel',
    trend_score: 83,
    popularity_score: 86,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
  {
    id: 10,
    career_name_th: 'นักกายภาพบำบัด',
    career_name_en: 'Physical Therapist',
    category: 'อาชีพสายบริการเฉพาะทาง',
    description: 'ช่วยฟื้นฟูสมรรถภาพ ลดอาการเจ็บ และวางแผนการเคลื่อนไหวที่เหมาะกับผู้รับบริการ',
    required_skills_json: '["health_care","empathy","service_minded"]',
    interest_tags_json: '["health","helping"]',
    personality_tags_json: '["empathy","service_minded"]',
    education_hint: 'ต้องเรียนสายสุขภาพที่เกี่ยวข้องและมีใบประกอบวิชาชีพตามเกณฑ์',
    roadmap: 'ศึกษาหลักสูตรที่รับรอง -> ฝึก anatomy พื้นฐาน -> สังเกตงาน -> ฝึกสื่อสารกับผู้ป่วย -> เก็บเคสฝึกงาน',
    trend_score: 84,
    popularity_score: 75,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
  {
    id: 11,
    career_name_th: 'ผู้ดูแลผู้สูงอายุ',
    career_name_en: 'Elderly Caregiver',
    category: 'อาชีพสายบริการเฉพาะทาง',
    description: 'ดูแลกิจวัตร สุขภาวะ และความปลอดภัยของผู้สูงอายุด้วยความเข้าใจและรับผิดชอบ',
    required_skills_json: '["empathy","service_minded","health_care"]',
    interest_tags_json: '["health","helping"]',
    personality_tags_json: '["empathy","service_minded"]',
    education_hint: 'เหมาะกับผู้ใจเย็น รับผิดชอบ และพร้อมเรียนทักษะการดูแลพื้นฐาน',
    roadmap: 'เรียน basic care -> ฝึกปฐมพยาบาล -> เรียนสื่อสารกับครอบครัว -> ฝึกเคสจำลอง -> ขอใบรับรองที่เกี่ยวข้อง',
    trend_score: 89,
    popularity_score: 80,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
  {
    id: 12,
    career_name_th: 'ที่ปรึกษาด้านสุขภาพ',
    career_name_en: 'Health Advisor',
    category: 'อาชีพสายบริการเฉพาะทาง',
    description: 'ให้คำแนะนำด้านสุขภาพเชิงป้องกัน ไลฟ์สไตล์ และการปรับพฤติกรรมอย่างเหมาะสม',
    required_skills_json: '["health_care","communication","empathy"]',
    interest_tags_json: '["health","helping","business"]',
    personality_tags_json: '["empathy","communication"]',
    education_hint: 'ควรมีความรู้สุขภาพที่ถูกต้อง ขอบเขตวิชาชีพชัดเจน และอ้างอิงแหล่งข้อมูลได้',
    roadmap: 'เรียน health literacy -> ฝึก coaching conversation -> ทำแผนสุขภาพ mock -> ศึกษาจริยธรรม -> ทำ content ให้ความรู้',
    trend_score: 81,
    popularity_score: 77,
    source_name: 'Vercel demo fallback',
    source_url: '',
    active_status: 1,
  },
];

const state = {
  nextPlayerId: 1,
  nextSessionId: 1,
  players: [],
  sessions: [],
  scores: new Map(),
  recommendations: new Map(),
};

export const memoryStore = {
  startPlayer(input) {
    const player_id = state.nextPlayerId++;
    const session_id = state.nextSessionId++;
    state.players.push({
      id: player_id,
      uuid: crypto.randomUUID(),
      consent_status: input.consent_status,
      gender: input.gender,
      created_at: new Date().toISOString(),
    });
    state.sessions.push({ id: session_id, player_id, completed_status: 0 });
    return { player_id, session_id };
  },
  saveProfile(input) {
    const player = state.players.find((item) => item.id === input.player_id);
    if (player) Object.assign(player, input);
    return { ok: true };
  },
  saveScore(input) {
    state.scores.set(input.session_id, input.scores);
    return { ok: true };
  },
  saveEvent() {
    return { ok: true };
  },
  saveRecommendations(sessionId, recommendations) {
    state.recommendations.set(sessionId, recommendations);
  },
  getRecommendations(sessionId) {
    return state.recommendations.get(sessionId) || [];
  },
  dashboard() {
    return {
      total_players: state.players.length,
      players_today: state.players.length,
      completed_sessions: [...state.recommendations.keys()].length,
      top_provinces: [],
      top_recommended_careers: [],
    };
  },
};
