USE career_quest_2026;

INSERT INTO admin_users (username, password_hash, role)
VALUES ('admin', '$2b$10$CwTycUXWue0Thq9StjUM0uJ8YedIdmh5k.O6Kf.DnZTdlzUqDLkTu', 'admin')
ON DUPLICATE KEY UPDATE username = username;

INSERT INTO careers
(career_name_th, career_name_en, category, description, required_skills_json, interest_tags_json,
 personality_tags_json, education_hint, roadmap, trend_score, popularity_score, source_name, source_url, active_status)
VALUES
('นักวิเคราะห์ข้อมูล', 'Data Analyst', 'สายเทคโนโลยีและดิจิทัล',
 'แปลงข้อมูลให้เป็น insight เพื่อช่วยตัดสินใจในธุรกิจ นโยบาย หรือบริการสาธารณะ',
 '["analytical","technology","communication"]', '["data","technology","business"]',
 '["analytical","communication"]', 'เหมาะกับผู้สนใจสถิติ spreadsheet, SQL, dashboard หรือ data storytelling',
 'เริ่มจาก Spreadsheet → SQL เบื้องต้น → ทำ dashboard → วิเคราะห์ dataset จริง → ทำ portfolio 2-3 ชิ้น',
 88, 86, 'MVP seed based on project brief', '', 1),
('นักพัฒนาซอฟต์แวร์', 'Software Developer', 'สายเทคโนโลยีและดิจิทัล',
 'สร้างเว็บ แอป และระบบดิจิทัลที่แก้ปัญหาให้ผู้ใช้หรือองค์กร',
 '["technology","analytical","independence"]', '["technology","business"]',
 '["technology","independence"]', 'เริ่มได้จาก HTML/CSS/JavaScript แล้วต่อยอด React, API และฐานข้อมูล',
 'ฝึกเขียนเว็บเล็ก ๆ → เชื่อม API → ทำระบบ login mock → deploy portfolio → อ่าน code review',
 90, 88, 'MVP seed based on project brief', '', 1),
('วิศวกรปัญญาประดิษฐ์', 'AI Engineer', 'สายเทคโนโลยีและดิจิทัล',
 'ออกแบบระบบ AI ที่ช่วยวิเคราะห์ สร้างคำตอบ หรืออัตโนมัติงานบางส่วนอย่างรับผิดชอบ',
 '["technology","analytical","creativity"]', '["technology","data"]',
 '["technology","analytical"]', 'ต้องมีพื้นฐาน programming, data, model evaluation และจริยธรรม AI',
 'เรียน Python → data preprocessing → ใช้ API/LLM → ทดลอง model evaluation → ทำ AI assistant prototype',
 94, 84, 'MVP seed based on project brief', '', 1),
('ผู้เชี่ยวชาญ SEO', 'SEO Specialist', 'สายการตลาดออนไลน์',
 'วิเคราะห์คำค้นหาและปรับเนื้อหาให้คนเจอเว็บไซต์ผ่าน search engine มากขึ้น',
 '["analytical","content","business"]', '["marketing","data","content"]',
 '["analytical","business"]', 'เหมาะกับคนที่ชอบภาษา ข้อมูล และพฤติกรรมผู้ใช้',
 'เรียน keyword research → ปรับบทความ → วัดผล analytics → ทำ content plan → ทดลอง A/B headline',
 82, 80, 'MVP seed based on project brief', '', 1),
('คอนเทนต์ครีเอเตอร์', 'Content Creator', 'สายการตลาดออนไลน์',
 'เล่าเรื่อง สร้างสื่อ และออกแบบเนื้อหาให้แบรนด์หรือสังคมเข้าใจง่ายและน่าติดตาม',
 '["creativity","content","communication"]', '["art","marketing","content"]',
 '["creativity","communication"]', 'เหมาะกับคนที่ชอบเล่าเรื่อง ภาพ เสียง วิดีโอ หรือคอนเทนต์สั้น',
 'เลือก niche → ทำ content calendar → ผลิตคลิป/โพสต์ → อ่าน analytics → ปรับ format ให้ดีขึ้น',
 86, 90, 'MVP seed based on project brief', '', 1),
('นักการตลาด Performance', 'Performance Marketer', 'สายการตลาดออนไลน์',
 'วางแผน ยิงแคมเปญ และวิเคราะห์ผลโฆษณาออนไลน์ด้วยตัวเลข',
 '["business","analytical","communication"]', '["marketing","data","business"]',
 '["business","analytical"]', 'ควรเข้าใจ funnel, ads platform, analytics และการทดลองแบบวัดผลได้',
 'เรียน marketing funnel → ตั้ง campaign mock → อ่าน metric → ทำรายงาน insight → optimize budget',
 87, 82, 'MVP seed based on project brief', '', 1),
('นักเขียนบทความ', 'Article Writer', 'อาชีพอิสระ / Freelance',
 'เขียนบทความให้ความรู้ รีวิว หรือสื่อสารเรื่องยากให้เข้าใจง่าย',
 '["content","creativity","communication"]', '["art","content","freelance"]',
 '["creativity","independence"]', 'เหมาะกับผู้ชอบค้นคว้า เขียน และจัดโครงเรื่อง',
 'ฝึกเขียนบทความ 800 คำ → ทำ portfolio → เรียน SEO พื้นฐาน → รับ brief → ปรับงานจาก feedback',
 76, 78, 'MVP seed based on project brief', '', 1),
('นักออกแบบกราฟิก', 'Graphic Designer', 'อาชีพอิสระ / Freelance',
 'ออกแบบภาพ สื่อ และ visual identity ให้สื่อสารชัดและน่าจดจำ',
 '["creativity","communication","business"]', '["art","marketing","freelance"]',
 '["creativity","independence"]', 'เหมาะกับผู้สนใจภาพ สี typography และ brand communication',
 'เรียน design principles → ทำ poster/social set → ฝึก brief จริง → ทำ portfolio → รับ feedback',
 78, 82, 'MVP seed based on project brief', '', 1),
('นักตัดต่อวิดีโอ', 'Video Editor', 'อาชีพอิสระ / Freelance',
 'เรียบเรียงภาพ เสียง และจังหวะให้คอนเทนต์น่าสนใจและเล่าเรื่องได้ดี',
 '["content","creativity","technology"]', '["art","content","freelance"]',
 '["creativity","independence"]', 'เหมาะกับผู้ชอบ storytelling, rhythm และเครื่องมือสร้างสื่อ',
 'ฝึกตัดคลิปสั้น → เรียน sound/title → ทำ before-after reel → ทดลอง format หลายแบบ → ทำ showreel',
 83, 86, 'MVP seed based on project brief', '', 1),
('นักกายภาพบำบัด', 'Physical Therapist', 'อาชีพสายบริการเฉพาะทาง',
 'ช่วยฟื้นฟูสมรรถภาพ ลดอาการเจ็บ และวางแผนการเคลื่อนไหวที่เหมาะกับผู้รับบริการ',
 '["health_care","empathy","service_minded"]', '["health","helping"]',
 '["empathy","service_minded"]', 'ต้องเรียนสายสุขภาพที่เกี่ยวข้องและมีใบประกอบวิชาชีพตามเกณฑ์',
 'ศึกษาหลักสูตรที่รับรอง → ฝึก anatomy พื้นฐาน → สังเกตงาน → ฝึกสื่อสารกับผู้ป่วย → เก็บเคสฝึกงาน',
 84, 75, 'MVP seed based on project brief', '', 1),
('ผู้ดูแลผู้สูงอายุ', 'Elderly Caregiver', 'อาชีพสายบริการเฉพาะทาง',
 'ดูแลกิจวัตร สุขภาวะ และความปลอดภัยของผู้สูงอายุด้วยความเข้าใจและรับผิดชอบ',
 '["empathy","service_minded","health_care"]', '["health","helping"]',
 '["empathy","service_minded"]', 'เหมาะกับผู้ใจเย็น รับผิดชอบ และพร้อมเรียนทักษะการดูแลพื้นฐาน',
 'เรียน basic care → ฝึกปฐมพยาบาล → เรียนสื่อสารกับครอบครัว → ฝึกเคสจำลอง → ขอใบรับรองที่เกี่ยวข้อง',
 89, 80, 'MVP seed based on project brief', '', 1),
('ที่ปรึกษาด้านสุขภาพ', 'Health Advisor', 'อาชีพสายบริการเฉพาะทาง',
 'ให้คำแนะนำด้านสุขภาพเชิงป้องกัน ไลฟ์สไตล์ และการปรับพฤติกรรมอย่างเหมาะสม',
 '["health_care","communication","empathy"]', '["health","helping","business"]',
 '["empathy","communication"]', 'ควรมีความรู้สุขภาพที่ถูกต้อง ขอบเขตวิชาชีพชัดเจน และอ้างอิงแหล่งข้อมูลได้',
 'เรียน health literacy → ฝึก coaching conversation → ทำแผนสุขภาพ mock → ศึกษาจริยธรรม → ทำ content ให้ความรู้',
 81, 77, 'MVP seed based on project brief', '', 1)
ON DUPLICATE KEY UPDATE career_name_th = VALUES(career_name_th);
